### ISSUE TITLE
Forced CSS and Elements

### ISSUE THREAD

**Issue by UWarbs** [enki-com/react-search-input#6]
Hey, I love this module, thanks for making it. The functionality is great but I'm curious why you decided to create 2 divs and a span when all it needs is the input element:  
React.createElement('input', {type: this.props.inputType || 'search',
              value: this.state.searchTerm,
              onChange: this.updateSearch, className: 'search-field',
              placeholder: this.props.placeholder})

Same question why you default to a className and css for the input? The functionality is great but I think most people want to style their inputs differently than this without having to override the defaults.

Have you thought about adding an option for default css/elements or just the input element with no class or css? I could make a pull request if you'd like.

**Comment by mathieudutour** [comment]
Yeah it was just to fit our design (it was first a component part of our app that i took out because it might interest other people, you for instance ;) ).
I'm happy to accept a PR if you can maintain the same design of the example without adding markup around `<Search />` (i don't want `<div><Search /><div`).

**Comment by UWarbs** [comment]
Well that makes complete sense. I added my functionality, just changed the .js file. I can update the README and test.js as well if you choose to accept.
Thanks
